spring:
  application:
    name: yitu-client-provider

eureka:
  client:
    service-url:
      defaultZone: http://marx:123456@localhost:8080/eureka
  instance:
    prefer-ip-address: true
server:
  port: 8083
